---
- name: Create a folder and download jenkins.war into it
  hosts: all
  tasks:
    - name: Create a folder
      file:
        name: /tmp/dir1
        state: directory
    - name: Downlaod jenkins.war into the above created folder
      get_url:
        url: https://get.jenkins.io/war-stable/2.492.1/jenkins.war
        dest: /tmp/dir1

...
