---
- name: Create a user on all servers
  hosts: appserver
  tasks:
    - name: Create user
      user:
        name: Ravi
        password: intelliqit
        uid: 9999
        home: /tmp/Ravi
        comment: "A normal user"
        shell: /bin/bash
...
